package com.zytec.upload.dao;

import java.util.List;

import com.zytec.upload.model.Picture;

public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C##BASEDATA.R_PICTURE
     *
     * @mbggenerated
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C##BASEDATA.R_PICTURE
     *
     * @mbggenerated
     */
    int insertSelective(Picture record);
    
    int realInsert(Picture record);
    
    int updateByOfAndType(Picture record);
    
    int deleteByOfAndType(Picture record);
    
    List<Picture> selectPictureName(Picture record);
    
    String selectByOfAndType(Picture record);
    
    int selectExists(Picture record);
}