package com.zytec.upload.model;

import java.util.Date;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##BASEDATA.R_PICTURE.P_ID
     *
     * @mbggenerated
     */
    private Short pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##BASEDATA.R_PICTURE.P_OF
     *
     * @mbggenerated
     */
    private String pOf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##BASEDATA.R_PICTURE.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##BASEDATA.R_PICTURE.DRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##BASEDATA.R_PICTURE.TJR
     *
     * @mbggenerated
     */
    private String tjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##BASEDATA.R_PICTURE.TJSJ
     *
     * @mbggenerated
     */
    private Date tjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##BASEDATA.R_PICTURE.XGR
     *
     * @mbggenerated
     */
    private String xgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C##BASEDATA.R_PICTURE.XGSJ
     *
     * @mbggenerated
     */
    private String xgsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##BASEDATA.R_PICTURE.P_ID
     *
     * @return the value of C##BASEDATA.R_PICTURE.P_ID
     *
     * @mbggenerated
     */
    public Short getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##BASEDATA.R_PICTURE.P_ID
     *
     * @param pId the value for C##BASEDATA.R_PICTURE.P_ID
     *
     * @mbggenerated
     */
    public void setpId(Short pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##BASEDATA.R_PICTURE.P_OF
     *
     * @return the value of C##BASEDATA.R_PICTURE.P_OF
     *
     * @mbggenerated
     */
    public String getpOf() {
        return pOf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##BASEDATA.R_PICTURE.P_OF
     *
     * @param pOf the value for C##BASEDATA.R_PICTURE.P_OF
     *
     * @mbggenerated
     */
    public void setpOf(String pOf) {
        this.pOf = pOf == null ? null : pOf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##BASEDATA.R_PICTURE.TYPE
     *
     * @return the value of C##BASEDATA.R_PICTURE.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##BASEDATA.R_PICTURE.TYPE
     *
     * @param type the value for C##BASEDATA.R_PICTURE.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##BASEDATA.R_PICTURE.DRESS
     *
     * @return the value of C##BASEDATA.R_PICTURE.DRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##BASEDATA.R_PICTURE.DRESS
     *
     * @param dress the value for C##BASEDATA.R_PICTURE.DRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##BASEDATA.R_PICTURE.TJR
     *
     * @return the value of C##BASEDATA.R_PICTURE.TJR
     *
     * @mbggenerated
     */
    public String getTjr() {
        return tjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##BASEDATA.R_PICTURE.TJR
     *
     * @param tjr the value for C##BASEDATA.R_PICTURE.TJR
     *
     * @mbggenerated
     */
    public void setTjr(String tjr) {
        this.tjr = tjr == null ? null : tjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##BASEDATA.R_PICTURE.TJSJ
     *
     * @return the value of C##BASEDATA.R_PICTURE.TJSJ
     *
     * @mbggenerated
     */
    public Date getTjsj() {
        return tjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##BASEDATA.R_PICTURE.TJSJ
     *
     * @param tjsj the value for C##BASEDATA.R_PICTURE.TJSJ
     *
     * @mbggenerated
     */
    public void setTjsj(Date tjsj) {
        this.tjsj = tjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##BASEDATA.R_PICTURE.XGR
     *
     * @return the value of C##BASEDATA.R_PICTURE.XGR
     *
     * @mbggenerated
     */
    public String getXgr() {
        return xgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##BASEDATA.R_PICTURE.XGR
     *
     * @param xgr the value for C##BASEDATA.R_PICTURE.XGR
     *
     * @mbggenerated
     */
    public void setXgr(String xgr) {
        this.xgr = xgr == null ? null : xgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C##BASEDATA.R_PICTURE.XGSJ
     *
     * @return the value of C##BASEDATA.R_PICTURE.XGSJ
     *
     * @mbggenerated
     */
    public String getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C##BASEDATA.R_PICTURE.XGSJ
     *
     * @param xgsj the value for C##BASEDATA.R_PICTURE.XGSJ
     *
     * @mbggenerated
     */
    public void setXgsj(String xgsj) {
        this.xgsj = xgsj == null ? null : xgsj.trim();
    }
}